=== ravijee/cirse/trunk/Cirse/doctypes/dtdUniverse.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT universe (head?,content)>
<!ATTLIST universe version CDATA #REQUIRED>
    <!ELEMENT head (name,creator?)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT creator (#PCDATA)>
    <!ELEMENT content (background,limits,light+,object*)>
        <!ELEMENT background (#PCDATA)>
        <!ATTLIST background type (color|image) "color"
                             src CDATA #IMPLIED
        >
        <!ELEMENT limits (appearance)> <!-- "alto, ancho, profundidad" -->
        <!ATTLIST limits width CDATA #REQUIRED
                         height CDATA #REQUIRED
                         deepness CDATA #REQUIRED
                         thickness CDATA #REQUIRED
        >
            <!ELEMENT appearance (material?, texture?)>
                <!ELEMENT material (ambient, emissive, diffuse, specular, shininess)>
                    <!ELEMENT ambient  (#PCDATA)>
                    <!ELEMENT emissive (#PCDATA)>
                    <!ELEMENT diffuse  (#PCDATA)>
                    <!ELEMENT specular (#PCDATA)>
                    <!ELEMENT shininess (#PCDATA)>
                <!ELEMENT texture EMPTY>
                <!ATTLIST texture src CDATA #REQUIRED
                                  enabled (true|false) "true">
        <!ELEMENT light (color,position?,atenuation?,direction?)>
        <!ATTLIST light type (ambient|point|directional) "ambient">
            <!ELEMENT color (#PCDATA)> <!-- r, g, b -->
            <!ELEMENT position (#PCDATA)> <!-- x, y, z -->
            <!ELEMENT direction (#PCDATA)>
            <!ELEMENT atenuation (#PCDATA)> <!-- constant, linear, quadratic -->
        <!ELEMENT object (objPos?, angles?)>
        <!ATTLIST object type (arm|graspable|util) "util"
                         src CDATA #REQUIRED
                         id  CDATA #REQUIRED
                         scale CDATA #IMPLIED
                         name CDATA #IMPLIED
        >
            <!ELEMENT objPos (#PCDATA)>
            <!ELEMENT angles (#PCDATA)>
            <!ATTLIST angles measure (degrees|radians) "degrees">

=== ravijee/cirse/trunk/Cirse/environment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE universe SYSTEM "doctypes/dtdUniverse.dtd">
<universe version="1.0">
    <content>
        <background type="color" src="texture1.png">
            1, 1, 1
        </background>
        <limits width="8" height="5" deepness="6" thickness="0.01">
            <appearance>
               <!--<material>
                    <ambient>1,0,1</ambient>
                    <emissive>0, 0, 0</emissive>
                    <diffuse>0.37, 0.37, 0.37</diffuse>
                    <specular>0.89, 0.89, 0.89</specular>
                    <shininess>1</shininess>
                 </material>-->
               <texture src="texture3.jpg"/>
            </appearance>
        </limits>
        <light type="ambient">
            <color>1, 0, 0</color>
        </light>
        <light type="directional">
            <color>1, 0, 1</color>
            <position>0, 0, 0</position>
        </light>
        <light type="point">
            <color>0, 1, 1</color>
            <position>0, 0, 0</position>
            <atenuation>1, 0, 0</atenuation>
        </light>
        <object src="arm.xml" id="2" type="arm" scale='0.005'>
            <objPos>3, 0, 0</objPos>
            <angles>12, 34, 62</angles>
        </object>
        <object src="designs/Flecha.dae" id="3" type='furniture' scale="0.04">
            <objPos>1, 1, 1</objPos>
        </object>
    </content>
</universe>
