=== ravijee/cirse/Cirse/doctypes/dtdArm.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT arm       (head?,content)>
<!ATTLIST arm           version CDATA #REQUIRED>
<!ELEMENT head      (name,creator?)>
<!ELEMENT name      (#PCDATA)>
<!ELEMENT creator   (#PCDATA)>
<!ELEMENT content   (support, position,(piece | joint)+)>
<!ELEMENT support   (#PCDATA)>
<!ELEMENT piece     (position, orientation, friction*)>
<!ATTLIST piece         type (segment|joint|finger|palm) "segment"
                        src CDATA #REQUIRED
>
<!ELEMENT joint    (position, orientation, friction*, jorientation*, (piece | joint)*)>
<!ATTLIST joint         src CDATA #REQUIRED
                        motion (rotational|translational) "rotational"
                        axis (x|y|z) "x"
>
<!ELEMENT position  (#PCDATA)>
<!ELEMENT orientation (#PCDATA)>
<!ELEMENT jorientation (#PCDATA)>
<!ATTLIST jorientation class (min|max|current) "current">
<!ELEMENT friction  (#PCDATA)>

=== ravijee/cirse/trunk/Cirse/prueba2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE arm PUBLIC "-//Entorno3D//doctypes/dtdArm.dtd" "http://monkeyarm.googlecode.com/files/dtdArm.dtd">
<arm version="1.0">
    <content>
        <support>0.0, -1.0, 0.0</support>
        <position>0.0, 0.0, 0.0</position>
        <joint src="designs/JntBase.dae" axis="y" motion="rotational">
            <position>0.0, 0.0, 0.0</position>
            <orientation>0.0, 0.0, 0.0</orientation>
            <jorientation class="current">0.0</jorientation>
            <jorientation class="min">0.0</jorientation>
            <jorientation class="max">360.0</jorientation>
            <joint src="designs/JntNormal1.dae" axis="x" motion="rotational">
                <position>0.0, 0.44000000000000006, 0.0</position>
                <orientation>0.0, 0.0, 0.0</orientation>
                <jorientation class="current">320.0</jorientation>
                <jorientation class="min">320.0</jorientation>
                <jorientation class="max">440.0</jorientation>
                <piece src="designs/sgmNormal1.dae" type="segment">
                    <position>0.03, 0.52, -0.41000000000000014</position>
                    <orientation>0.0, 0.0, 0.0</orientation>
                </piece>
                <joint src="designs/JntNormal1.dae" axis="x" motion="rotational">
                    <position>0.060000000000000005, 1.05, -0.7800000000000002</position>
                    <orientation>0.0, 183.0, 0.0</orientation>
                    <jorientation class="current">360.0</jorientation>
                    <jorientation class="min">200.0</jorientation>
                    <jorientation class="max">360.0</jorientation>
                    <piece src="designs/sgmNormal2.dae" type="segment">
                        <position>-0.04, -0.35000000000000003, 1.04</position>
                        <orientation>0.0, 2.0, 0.0</orientation>
                    </piece>
                    <joint src="designs/JntArm1.dae" axis="x" motion="rotational">
                        <position>-0.13999999999999999, -0.77, 2.3200000000000003</position>
                        <orientation>0.0, 0.0, 0.0</orientation>
                        <jorientation class="current">379.0</jorientation>
                        <jorientation class="min">300.0</jorientation>
                        <jorientation class="max">420.0</jorientation>
                        <piece src="designs/PalmNormal1.dae" type="segment">
                            <position>-0.040000000000000015, -0.17, 0.3699999999999998</position>
                            <orientation>0.0, 0.0, 0.0</orientation>
                        </piece>
                        <joint src="designs/FngJntNmlLeft.dae" axis="y" motion="rotational">
                            <position>0.12999999999999998, -0.03, 0.8800000000000001</position>
                            <orientation>0.0, 11.0, 0.0</orientation>
                            <jorientation class="current">356.0</jorientation>
                            <jorientation class="min">330.0</jorientation>
                            <jorientation class="max">390.0</jorientation>
                            <piece src="designs/FingerNrm1.dae" type="segment">
                                <position>0.09, 0.0, 0.4200000000000002</position>
                                <orientation>0.0, 0.0, 0.0</orientation>
                            </piece>
                        </joint>
                        <joint src="designs/FngJntNmlRight.dae" axis="y" motion="rotational">
                            <position>-0.36, 0.0, 0.8700000000000001</position>
                            <orientation>0.0, 0.0, 0.0</orientation>
                            <jorientation class="current">361.0</jorientation>
                            <jorientation class="min">340.0</jorientation>
                            <jorientation class="max">380.0</jorientation>
                            <piece src="designs/FingerNrm1.dae" type="segment">
                                <position>-0.07, 0.010000000000000028, 0.44000000000000017</position>
                                <orientation>0.0, 55.0, 0.0</orientation>
                            </piece>
                        </joint>
                    </joint>
                </joint>
            </joint>
        </joint>
    </content>
</arm>

=== ravijee/cirse/trunk/Cirse/prueba.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE arm PUBLIC "-//Entorno3D//doctypes/dtdArm.dtd//EN" "http://monkeyarm.googlecode.com/files/dtdArm.dtd">
<arm version="1.0">
<content>
<support>0.0, -1.0, 0.0</support>
<position>0.0, 0.0, 0.0</position>
<joint src="designs/JntBase.dae" axis="x" motion="rotational">
<position>0.0, 0.0, 0.0</position>
<orientation>0.0, 0.0, 0.0</orientation>
<jorientation class="current">0.0</jorientation>
<jorientation class="min">0.0</jorientation>
<jorientation class="max">360.0</jorientation>
<joint src="designs/JntNormal1.dae" axis="x" motion="rotational">
<position>0.0, 0.45000000000000023, 0.0</position>
<orientation>0.0, 0.0, 0.0</orientation>
<jorientation class="current">0.0</jorientation>
<jorientation class="min">0.0</jorientation>
<jorientation class="max">360.0</jorientation>
<piece src="designs/sgmNormal1.dae" type="segment">
<position>0.05, 0.53, -0.3999999999999998</position>
<orientation>0.0, 0.0, 0.0</orientation>
</piece>
<joint src="designs/JntNormal1.dae" axis="x" motion="rotational">
<position>0.0, 0.8599999999999999, -1.0799999999999998</position>
<orientation>0.0, 0.0, 0.0</orientation>
<jorientation class="current">303.0</jorientation>
<jorientation class="min">0.0</jorientation>
<jorientation class="max">360.0</jorientation>
<piece src="designs/sgmNormal1.dae" type="segment">
<position>0.18000000000000002, 0.53, -0.3300000000000001</position>
<orientation>0.0, 0.0, 0.0</orientation>
</piece>
</joint>
</joint>
</joint>
</content>
</arm>

=== ravijee/cirse/Cirse/designs/Arm2/Arm2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE arm PUBLIC "-//Entorno3D//doctypes/dtdArm.dtd//EN" "http://monkeyarm.googlecode.com/files/dtdArm.dtd">
<arm version="1.0">
<content>
<support>0.0, -1.0, 0.0</support>
<position>0.0, 0.0, 0.0</position>
<joint src="Segment1.dae" axis="y" motion="rotational">
<position>0.0, 0.55, 0.0</position>
<orientation>0.0, 0.0, 0.0</orientation>
<jorientation class="current">192.0</jorientation>
<jorientation class="min">0.0</jorientation>
<jorientation class="max">360.0</jorientation>
<joint src="Joint1.dae" axis="y" motion="translational">
<position>0.0, -0.4, 0.0</position>
<orientation>0.0, 0.0, 0.0</orientation>
<jorientation class="current">0.8999999798834324</jorientation>
<jorientation class="min">0.0</jorientation>
<jorientation class="max">90.0</jorientation>
<piece src="Segment2.dae" type="segment">
<position>0.7200000000000001, 0.0, 0.0</position>
<orientation>90.0, 180.0, 90.0</orientation>
</piece>
<joint src="Joint2.dae" axis="x" motion="translational">
<position>0.28000000000000014, 0.0, 0.0</position>
<orientation>0.0, 0.0, 90.0</orientation>
<jorientation class="current">0.6099999863654375</jorientation>
<jorientation class="min">1.0</jorientation>
<jorientation class="max">90.0</jorientation>
<joint src="Joint1.dae" axis="x" motion="rotational">
<position>0.0, 0.0, 0.0</position>
<orientation>0.0, 0.0, 90.0</orientation>
<jorientation class="current">0.0</jorientation>
<jorientation class="min">0.0</jorientation>
<jorientation class="max">360.0</jorientation>
</joint>
</joint>
</joint>
</joint>
</content>
</arm>
