=== ravijee/cirse/Cirse/doctypes/dtdPalette.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT palette (category+)>
<!ELEMENT category (item+)>
<!ATTLIST category title CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item title CDATA #REQUIRED
               file  CDATA #REQUIRED
               img   CDATA #IMPLIED>

=== ravijee/cirse/trunk/Cirse/piecesPalette.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : piecesPalette.xml
    Created on : 5 de abril de 2011, 13:49
    Author     : pablo
    Description:
        Purpose of the document follows.
-->

<!DOCTYPE palette SYSTEM 'doctypes/dtdPalette.dtd'>
<palette>
    <category title="Segments">
        <item file="designs/sgmNormal1.dae" img="designs/imgs/sgmNormal1.png" title="Segment 1">
            Basic segment.
        </item>
        <item file="designs/sgmNormal2.dae" img="designs/imgs/sgmNormal2.png" title="Segment 2">
            Basic segment.
        </item>
    </category>
    <category title="Joints">
        <item file="designs/JntBase.dae" img="designs/imgs/JntBase.png" title="Joint Base">
            Joint used in the base of the arm.
        </item>
        <item file="designs/JntNormal1.dae" img="designs/imgs/JntNormal1.png" title="Joint 1">
            Basic Joint.
        </item>
        <item file="designs/JntArm1.dae" img="designs/imgs/JntArm1.png" title="Joint of palm">
            Joint used before a palm.
        </item>
    </category>
    <category title="Fingers">
        <item file="designs/FingerNrm1.dae" img="designs/imgs/FingerNrm1.png" title="Finger 1">
            Basic Finger.
        </item>
        <item file="designs/FngJntNmlLeft.dae" img="designs/imgs/FngJntNmlLeft.png" title="Hand finger left">
            Finger used en the palm of the arm, left side.
        </item>
        <item file="designs/FngJntNmlRight.dae" img="designs/imgs/FngJntNmlRight.png" title="Hand finger roght">
            Finger used en the palm of the arm, right side.
        </item>
    </category>
    <category title="Palms">
        <item file="designs/PalmNormal1.dae" img="designs/imgs/PalmNormal1.png" title="Palm">
            Basic Palm.
        </item>
    </category>
</palette>
