=== ravijee/cirse/Cirse/doctypes/dtdUniverse.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT universe (head?,content)>
<!ATTLIST universe version CDATA #REQUIRED>
    <!ELEMENT head (name,creator?)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT creator (#PCDATA)>
    <!ELEMENT content (background,limits,light+,object*)>
        <!ELEMENT background (#PCDATA)>
        <!ATTLIST background src CDATA #IMPLIED>
        <!ELEMENT limits (width, height, deepness, thickness, appearance)> <!-- "alto, ancho, profundidad" -->
            <!ELEMENT width (#PCDATA)>
            <!ELEMENT height (#PCDATA)>
            <!ELEMENT deepness (#PCDATA)>
            <!ELEMENT thickness (#PCDATA)>
            <!ELEMENT appearance (material, texture?)>
                <!ELEMENT material (ambient, emissive, diffuse, specular, shininess)>
                    <!ELEMENT ambient  (#PCDATA)>
                    <!ELEMENT emissive (#PCDATA)>
                    <!ELEMENT diffuse  (#PCDATA)>
                    <!ELEMENT specular (#PCDATA)>
                    <!ELEMENT shininess (#PCDATA)>
                <!ELEMENT texture EMPTY>
                <!ATTLIST texture src CDATA #REQUIRED
                                  enabled (true|false) "true">
        <!ELEMENT light (color,position?,attenuation?,direction?)>
        <!ATTLIST light type (ambient|point|directional) "ambient">
            <!ELEMENT color (#PCDATA)> <!-- r, g, b -->
            <!ELEMENT position (#PCDATA)> <!-- x, y, z -->
            <!ELEMENT direction (#PCDATA)>
            <!ELEMENT attenuation (#PCDATA)> <!-- constant, linear, quadratic -->
        <!ELEMENT object (name?, scale, location, rotation)>
        <!ATTLIST object type (arm|pickable|furniture) "furniture"
                         src CDATA #REQUIRED>
            <!ELEMENT scale (#PCDATA)>
            <!ELEMENT location (#PCDATA)>
            <!ELEMENT rotation (#PCDATA)>

=== ravijee/cirse/Cirse/Env3.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE universe SYSTEM "doctypes/dtdUniverse.dtd">
<universe version="1.0">
    <content>
        <background src="texture3.jpg"/>
        <limits>
            <width>10.0</width>
            <height>15.0</height>
            <deepness>15.0</deepness>
            <thickness>0.05</thickness>
            <appearance>
                <material>
                    <ambient>1.0, 0.0, 1.0</ambient>
                    <emissive>0.0, 0.0, 0.0</emissive>
                    <diffuse>0.37, 0.37, 0.37</diffuse>
                    <specular>0.89, 0.89, 0.89</specular>
                    <shininess>1.0</shininess>
                </material>
            </appearance>
        </limits>
        <light type="ambient">
            <color>0.2, 1.0, 0.8</color>
            <position>0.0, 0.0, 0.0</position>
            <attenuation>0.0, 0.0, 0.0</attenuation>
        </light>
        <light type="directional">
            <color>0.6, 1.0, 0.2</color>
            <direction>0.0, 0.0, 0.0</direction>
        </light>
        <light type="point">
            <color>1.0, 1.0, 0.4</color>
            <position>1.0, 1.0, 1.0</position>
            <attenuation>1.0, 0.0, 0.0</attenuation>
        </light>
        <object src="designs\Flecha.dae" type="furniture">
            <scale>1.0</scale>
            <location>1.0, 2.0, 1.0</location>
            <rotation>180.0, 90.0, 90.0</rotation>
        </object>
    </content>
</universe>

=== ravijee/cirse/Cirse/Env2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document   : Env2.xml
    Created on : 8 de noviembre de 2011, 11:25 AM
    Author     : Karo
    Description:
        Purpose of the document follows.
-->

<!DOCTYPE universe SYSTEM "doctypes/dtdUniverse.dtd">
<universe version="1.0">
    <content>
        <background src="texture3.jpg">1, 1, 1</background>
        <limits>
            <width>8</width>
            <height>5</height>
            <deepness>6</deepness>
            <thickness>0.01</thickness>   
            <appearance>
               <material>
                    <ambient>1,0,1</ambient>
                    <emissive>0, 0, 0</emissive>
                    <diffuse>0.37, 0.37, 0.37</diffuse>
                    <specular>0.89, 0.89, 0.89</specular>
                    <shininess>1</shininess>
                 </material>
                <texture src="texture3.jpg" enabled="true"/>
            </appearance>
        </limits>
        <light type="ambient">
            <color>1, 0, 0</color>
        </light>
        <light type="directional">
            <color>1, 0, 1</color>
            <position>0, 0, 0</position>
        </light>
        <light type="point">
            <color>0, 1, 1</color>
            <position>0, 0, 0</position>
            <attenuation>1, 0, 0</attenuation>
        </light>
        <object src="designs/Flecha.dae" type='furniture'>
            <scale>1</scale>
            <location>1, 1, 1</location>
            <rotation>12, 12, 12</rotation>
        </object>
    </content>
</universe>
